server:
  port: 18120
#db config
spring:
  config:
    activate:
      on-profile: live
  messages:
    basename: classpath:message/cm
  data:
    mongodb:
      #uri: mongodb://192.168.0.101:30001,mongodb://192.168.0.101:30002,mongodb://192.168.0.101:30003
      #uri: mongodb+srv://admin:asdf1234@cluster0.qjn0e.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      #uri: mongodb://fzpprddocudbdmin:..themcompany2021!@fzp-prd-docudb-21-08-23.cluster-ccdquupkyiju.ap-northeast-2.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=true
      uri: mongodb://fzpprddocudbdmin:..themcompany2021!@fzp-prd-docudb-21-08-23.ccdquupkyiju.ap-northeast-2.docdb.amazonaws.com:27017/?retryWrites=false
      database: "orderRelay"
      timezone: 9
  security:
    key-pair: THE_M_COMPANY123
  jwt:
    secret: them7568!@34
    #1000 * 60 * 60 * 24 * 7 일주일
    tokenValid: 604800000
    #1000 * 60 * 60 * 24 * 2 일주일
    refreshTokenValid: 1209600000
  rabbitmq:
    host: b-756addac-fad4-43c2-bd05-717f82d9a78a.mq.ap-northeast-2.amazonaws.com # Amazon MQ
    port: 5671
    username: themDev
    password: theMcomp75^*
    queue-name: them-order
    topic-exchange-name: them-order-exchange
    virtual-host: /vesta
    ssl:
      enabled: true
  listener:
    simple:
      acknowledge-mode: manual

# 로그설정
logging:

  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %M %logger{35} - %msg%n"
  level:
    root: warn
    org.springframework.web: debug
    org.springframework.security: off
    com.them.orderrelay: debug
    java.sql: error
    jdbc: off
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: error
  file:
    path: /home/ec2-user/com-them-order-relay/logs
    name: ${logging.file.path}/order-relay.log
  logback:
    rollingpolicy:
      file-name-pattern: "${logging.file.path}/order.log.%d{yyyy-MM-dd}.%i.log.gz"
      max-size: 4GB
      max-history: 30





